services:
  core:
    build: ./core
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./config.env
    ports:
    - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./core:/app
  postgres:
    image: postgres:13
    env_file:
      - ./config.env
    volumes:
      - './data/postgres:/var/lib/postgresql/data'