version: '3'

services:
  core:
    build: ./core
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./config.env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./core:/app
  db:
    image: mysql:8
    expose:
      - 3306
    env_file:
      - ./config.env
    volumes:
      - ./data/mysql:/var/lib/mysql